#!/bin/bash
# A script to manage the SuperTalkie

function setCronJob() {
  cmd=$2
  sched=$1
  job="$sched $cmd"
  ( crontab -l | grep -v -F "$cmd" ; echo "$job" ) | crontab -
}

mgrRootCmd="/home/mumble/supertalkie-manager/supertalkie-manager"

if [ "$1" = "start" ]; then
  echo "Starting SuperTalkie"
  systemctl restart mumble.service
elif [ "$1" = "stop" ]; then
  echo "Stoping SuperTalkie"
  systemctl stop mumble.service
elif [ "$1" = "install" ]; then
  echo "Installing SuperTalkie Manager"
  setCronJob "0 20 * * *" "$mgrRootCmd stop"
  setCronJob "0 8 * * *" "$mgrRootCmd start"
elif [ "$1" = "set-stoptime" ]; then
  hour="$2"
  min="$3"
  echo "Setting SuperTalkie stop time to $hour:$min"
  setCronJob "$min $hour * * *" "$mgrRootCmd stop"
elif [ "$1" = "set-starttime" ]; then
  hour="$2"
  min="$3"
  echo "Setting SuperTalkie start time to $hour:$min"
  setCronJob "$min $hour * * *" "$mgrRootCmd start"
fi
