#!/bin/bash
# A script to manage the SuperTalkie

if [ "$1" = "start" ]; then
  echo "Starting SuperTalkie"
  systemctl restart mumble.service
elif [ "$1" = "stop" ]; then
  echo "Stoping SuperTalkie"
  systemctl stop mumble.service
fi
